events {}

http {
    #upstream frontend_cluster {
    #    least_conn;
    #    server front:3000;
    #}

    #upstream api_gateway_cluster {
    #    least_conn;
    #    server api-gateway:3000;
    #}

    upstream auth_service_cluster {
    #    least_conn;   # round-robin (à tour de rôle), mais on peut aussi utiliser least_conn pour équilibrer en fonction du nombre de connexions actives
        server auth-service:3001;
    }

    server {
        listen 80;

        # Frontend
        #location / {
        #    proxy_pass http://frontend_cluster;

        #    proxy_http_version 1.1;
        #    proxy_set_header Host $host;
        #    proxy_set_header X-Real-IP $remote_addr;
        #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #    proxy_set_header X-Forwarded-Proto $scheme;
        #}

        # API Gateway
        #location /api/ {
        #    proxy_pass http://api_gateway_cluster/;

        #    proxy_http_version 1.1;
        #    proxy_set_header Host $host;
        #    proxy_set_header X-Real-IP $remote_addr;
        #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #    proxy_set_header X-Forwarded-Proto $scheme;
        #}

        # Auth direct, utile pendant le dev tant que gateway pas finie
        location /auth/ {
            proxy_pass http://auth_service_cluster/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health Nginx
        location /health {
            return 200 '{"service":"nginx-load-balancer","status":"OK"}';
            add_header Content-Type application/json;
        }
    }
}